# New ports collection makefile for:   oneko
# Date created:        5 December 1994
# Whom:                asami
#
# $FreeBSD$
#

PORTNAME=      fs-utf8-patch
PORTVERSION=   0.1b
CATEGORIES=    sysutils
MASTER_SITES=  http://pagxir.cublog.cn

MAINTAINER=    pagxir@gmail.com
COMMENT=       A UTF-8 support patch for FreeBSD msdosfs/ntfs

MAN1=          fsutf8.1
MANCOMPRESSED= yes
USE_IMAKE=     yes

.include <bsd.port.mk>

